# Site settings
title: Omaha Coding Women
email: sandi.k.barr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  OCW is an organization which meets to discuss programming technologies and methods.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omahacodingwomen.com" # the base hostname & protocol for your site
twitter_username: omacodingwomen
github_username:  omacodingwomen

# Build settings
markdown: kramdown
